---
apiVersion: v2
name: snoopy
type: application
version: 0.2.0
appVersion: v0.6.14
description: |
  Snoopy subscribes to events on the Ethereum network you specify and
  spits out stats and information about blocks it has gathered since
  it started.

  ---

  How to get it;

  ~~~

  helm repo add snoopy https://dfroberg.github.io/snoopy/

  helm repo update

  ~~~

  Take a look;

  ~~~

  helm search repo snoopy

  ~~~

  How to install it;

  ~~~

  helm upgrade snoopy snoopy/snoopy \
        --install \
        --namespace snoopy \
        --create-namespace \
        --wait \
        --set snoopy.image.tag=latest \
        --set snoopy.ingress.enabled=true \
        --set snoopy.ingress.domain.prefix="" \
        --set snoopy.ingress.domain.base=snoopy.local \
        --set snoopy.metrics.enabled=true

  ~~~

  How to test it;

  ~~~

  helm test snoopy --namespace snoopy

  ~~~

home: https://github.com/dfroberg/snoopy
icon: https://cdn-images-1.medium.com/max/1600/1*-9mb3AKnKdcL_QD3CMnthQ.png
sources:
- https://github.com/dfroberg/snoopy/tree/master/snoopy
maintainers:
  - name: dfroberg
    email: danny@froberg.org

