---
common:
  # -- This is optional, will be populated by a random string if not defined or already present in a secret.
  snoopyApiToken: TestToken
  # -- Required: Infura Project ID
  projectId: YouForgotToSetYourProjectId
  # -- Required: Ethereum Network to listen on
  networkName: mainnet

snoopy:
  image:
    # -- Image Repository
    repository: "dfroberg/snoopy"
    # -- Image Tag
    tag: "v0.6.26"
    # -- Image pullPolicy
    pullPolicy: "Always"
  # -- Environment vars to set
  env:
    - name: "TZ"
      value: "Europe/Stockholm"
  ingress:
    # -- Enable ingress
    enabled: true
    # -- Ingress annotations
    annotations: {}
    # -- Ingress labels
    labels: {}
    #  nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # -- IngressClassName
    ingressClassName: "traefik"
    # -- Build host string
    domain:
      base: "snoopy.local"
      prefix: ""
      suffix: ""
  # snoopy service
  service:
    # -- Port number (Defaults to 9080)
    port: 9080
  metrics:
    # -- Enable if you wish to deploy prometheus metrics
    enabled: true
    # -- Port number (Defaults to 2112)
    port: 2112
  # -- Resource limits
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 1024Mi


