---
common:
  snoopyApiToken: TestToken

snoopy:
  image:
    repository: "dfroberg/snoopy"
    tag: "v0.6.8"
    pullPolicy: "Always"
  env:
    - name: "TZ"
      value: "Europe/Stockholm"
  ingress:
    enabled: true
    annotations: {}
    labels: {}
    ingressClassName: "traefik"
    domain:
      base: "snoopy.local"
      prefix: ""
      suffix: ""
  metrics:
    enabled: true
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 1024Mi


