---
# This should rather be delivered through an secrets engine or sops / age.
apiVersion: v1
kind: Secret
metadata:
  name: common-snoopy-secret
  namespace: $SNOOPY_NAMESPACE
  labels:
    app: snoopy
stringData:
  SNOOPY_API_TOKEN: $SNOOPY_API_TOKEN
  SNOOPY_PROJECT_ID: $SNOOPY_PROJECT_ID
