---
apiVersion: v1
kind: Secret
metadata:
  name: common-snoopy-secret
  namespace: "{{ .Release.Namespace }}"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
  labels:
    app: snoopy
data:
  SNOOPY_API_TOKEN: {{ include "common.snoopy-api-token" . | b64enc }}
  SNOOPY_PROJECT_ID: {{- .Values.snoopy.projectid | default "mainnet" }}

