---
apiVersion: v1
kind: ConfigMap
metadata:
  name: snoopy-config-map
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: snoopy
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
data:
  SNOOPY_NETWORK_NAME: {{- .Values.snoopy.networkname | default "mainnet" }}
