---
apiVersion: v1
kind: Service
metadata:
  name: snoopy-service
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: snoopy
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec:
  type: ClusterIP
  ports:
  - name: main
    port: {{ .Values.snoopy.service.port | default 9080 }}
    protocol: TCP
  - name: metrics
    port: {{ .Values.snoopy.metrics.port | default 9080 }}
    protocol: TCP
  selector:
    app: snoopy
