---
{{- if (.Values.snoopy.ingress.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snoopy-ingress
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: snoopy
    {{- with .Values.snoopy.ingress.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    {{- with .Values.snoopy.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.snoopy.ingress.ingressClassName }}
  rules:
    - host: {{ include "ingress.hostName" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: snoopy-service
                port:
                  number: {{ .Values.snoopy.service.port | default 9080 }}
{{- end -}}
