name: 'Docker Build Release'
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["release"]
    types: [completed]
jobs:
  docker:
    name: 'Build Docker Images'
    runs-on: ubuntu-latest
    if: {{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@b2391d37b4157fa4aa2e118d643f417910ff3242
        with:
          images: dfroberg/snoopy
      - name: Build and push snoopy
        uses: docker/build-push-action@v2
        with:
          context: src
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
