name: ci
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'src/**/*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8d56fe93cf3fd680736a906389438c1ed74d75f7
        with:
          github-token: ${{ secrets.PAT }}
          images: dfroberg/snoopy
      - name: Build and push snoopy
        uses: docker/build-push-action@v3
        with:
          context: src
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
