name: release
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  release-on-push:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          use_github_release_notes: true
          release_name: "Release <RELEASE_VERSION>"
          max_commits: 100
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"